name: Continuous Integration

on:
  pull_request:
    branches: ["main"]

jobs:
  continuous_integration_verification:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test Customer Service
        working-directory: ./microservices_project/customer
        run: |
          npm ci
          npm test

      - name: Test Products Service
        working-directory: ./microservices_project/products
        run: |
          npm ci
          npm test

      - name: Test Shopping Service
        working-directory: ./microservices_project/shopping
        run: |
          npm ci
          npm test
